### ISSUE TITLE
Default layout is not being used

### ISSUE THREAD

**Issue by NilsWinter** [comwes/mkpdfs-mkdocs-plugin#12]
I've been trying to replicate the very nice layout showcased on your website. However, if I try to generate the PDF, it runs smoothly without errors but somehow it's not applying any layout at all (just as if the css was missing completely).
I'm using the Material theme and I'm not specifying any additional or different css. 

Did I miss anything? Do I need to specify a custom css to get it looking right?

Thanks a lot!

**Comment by NilsWinter** [comment]
Okay, I think I just realized that it won't look like the PDF you showcased straight away but that I need to build my own css layout? I've copied and pasted your layout and it seems to work fine.

Or should some formatting be applied by default?

Thanks for nice work, by the way!
Cheers,
Nils

**Comment by gl-agnx** [comment]
Hi NIls,

I too ran into this issue. But it's straightforward to get this running. The problem is this, if you look at the details, you'll see that the package expects a report.css. Well, I don't see it being pulled. The repository contains a report.sass, which means one has to compile it

Now because there is an error with latest mkpdfs where the string type fails, I just went ahead and created a custom version of mkpdfs which definitively works (and I get PDF that's advertised)

(instructions for ubuntu)

1) Clone the latest mkpdfs repository

2) Install sass
sudo apt-get install sass

Install modularscale (you'll get complaints otherwise)

npm install modularscale-sass --save-dev

3) Apply commit c313b133f40afbcaf2a65bf0509f52822318dec6
This commit fixes the string type incompatibility. mkpdfs hasn't pulled the fix this commit has

go to design directory where report.sass is and do:
sass report.sass report.css

Hopefully this should build no problem and you'll have a nice report.css file
4)
now go up in directory. let's make sure that default mkpdfs is removed since you're installing this custom one:

pip uninstall mkpdfs-mkdocs

5) Now install mkpdfs that you built:

python setup.py install

With this, the mkpdfs-mkdocs with the fix for mkdocs 1.1 and latest material theme should be installed (upgrade each of them if needed).

Now try and build the docs for the repository. It should work (there are some css deprecation errors but it still works very nicely).

You can login to the server it creates and download the PDF. It's exactly what's advertised.

Unfortunately seems this project is dead. The maintainer isn't doing anything.
